# Site settings
title: Atelier NV Couture
description: L'atelier de création de Justaucorps de Nadège Vazeille
keywords: GRS, Couture, Justaucorps
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
